# Configuration MySQL
mysql.url=jdbc:mysql://localhost:3306/univ_scheduler?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
mysql.utilisateur=root
mysql.motdepasse=778512692
mysql.driver=com.mysql.cj.jdbc.Driver